"""role ustunini enum qilish

Revision ID: 71eeaf931a48
Revises: 9b699c87f7c4
Create Date: 2026-06-21 12:32:15.927351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71eeaf931a48'
down_revision: Union[str, Sequence[str], None] = '9b699c87f7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('USER', 'ADMIN', name='userrole'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('USER', 'ADMIN', name='userrole'),
               type_=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
